import * as XLSX from "xlsx";

export function exportToExcel<T extends Record<string, unknown>>(
  filename: string,
  rows: T[],
  meta: { generatedBy: string; filters?: Record<string, unknown> },
) {
  const wb = XLSX.utils.book_new();

  const metaRows: (string | number)[][] = [
    ["Generated By", meta.generatedBy],
    ["Generated At", new Date().toLocaleString()],
    ["Record Count", rows.length],
    [],
    ["Applied Filters"],
    ...Object.entries(meta.filters ?? {})
      .filter(([, v]) => v !== undefined && v !== null && v !== "" && v !== "all")
      .map(([k, v]) => [k, String(v)]),
  ];
  const metaSheet = XLSX.utils.aoa_to_sheet(metaRows);
  XLSX.utils.book_append_sheet(wb, metaSheet, "Info");

  const dataSheet = XLSX.utils.json_to_sheet(rows);
  XLSX.utils.book_append_sheet(wb, dataSheet, "Data");

  XLSX.writeFile(wb, `${filename}-${new Date().toISOString().slice(0, 10)}.xlsx`);
}
