import * as XLSX from "xlsx";

export type ExportProgress = {
  phase: "preparing" | "building" | "writing" | "done" | "retrying" | "cancelled";
  processed: number;
  total: number;
  message: string;
  attempt?: number;
};

export class ExportCancelledError extends Error {
  constructor() { super("Export cancelled"); this.name = "ExportCancelledError"; }
}

function checkAborted(signal?: AbortSignal) {
  if (signal?.aborted) throw new ExportCancelledError();
}

/**
 * Build an XLSX workbook in chunks, yielding to the event loop between chunks
 * so the UI can show progress. Returns a Blob (NOT auto-downloaded) so the
 * caller can show a "Download" button once ready.
 */
export async function buildExcelBlobAsync<T extends Record<string, unknown>>(
  rows: T[],
  meta: { generatedBy: string; filters?: Record<string, unknown> },
  onProgress?: (p: ExportProgress) => void,
  chunkSize = 500,
  signal?: AbortSignal,
): Promise<Blob> {
  return buildWithRetry(rows, meta, onProgress, chunkSize, 2, signal);
}

/**
 * Queue-style runner with automatic retry. The Excel build is CPU work, so a
 * "background queue" here means a single in-flight job that yields between
 * chunks and retries the whole job up to `maxAttempts` times on failure.
 */
export async function buildWithRetry<T extends Record<string, unknown>>(
  rows: T[],
  meta: { generatedBy: string; filters?: Record<string, unknown> },
  onProgress?: (p: ExportProgress) => void,
  chunkSize = 500,
  maxAttempts = 2,
  signal?: AbortSignal,
): Promise<Blob> {
  let attempt = 0;
  let lastErr: unknown;
  while (attempt <= maxAttempts) {
    try {
      checkAborted(signal);
      if (attempt > 0) {
        onProgress?.({
          phase: "retrying", processed: 0, total: rows.length, attempt: attempt + 1,
          message: `Retrying (attempt ${attempt + 1} of ${maxAttempts + 1})…`,
        });
        await new Promise((r) => setTimeout(r, 250 * attempt));
        checkAborted(signal);
      }
      return await buildOnce(rows, meta, onProgress, chunkSize, attempt + 1, signal);
    } catch (e) {
      if (e instanceof ExportCancelledError) {
        onProgress?.({ phase: "cancelled", processed: 0, total: rows.length, attempt: attempt + 1, message: "Cancelled" });
        throw e;
      }
      lastErr = e;
      attempt += 1;
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error(String(lastErr));
}

async function buildOnce<T extends Record<string, unknown>>(
  rows: T[],
  meta: { generatedBy: string; filters?: Record<string, unknown> },
  onProgress: ((p: ExportProgress) => void) | undefined,
  chunkSize: number,
  attempt: number,
  signal?: AbortSignal,
): Promise<Blob> {
  const total = rows.length;
  checkAborted(signal);
  onProgress?.({ phase: "preparing", processed: 0, total, attempt, message: "Preparing workbook…" });
  await tick();

  const wb = XLSX.utils.book_new();

  const metaRows: (string | number)[][] = [
    ["Generated By", meta.generatedBy],
    ["Generated At", new Date().toLocaleString()],
    ["Record Count", total],
    [],
    ["Applied Filters"],
    ...Object.entries(meta.filters ?? {})
      .filter(([, v]) => v !== undefined && v !== null && v !== "" && v !== "all")
      .map(([k, v]) => [k, String(v)]),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(metaRows), "Info");

  // Build header from first row keys
  const dataSheet = XLSX.utils.aoa_to_sheet(
    total === 0 ? [[]] : [Object.keys(rows[0])],
  );

  let processed = 0;
  for (let i = 0; i < total; i += chunkSize) {
    checkAborted(signal);
    const slice = rows.slice(i, i + chunkSize);
    const aoa = slice.map((r) => Object.values(r) as (string | number | boolean | null)[]);
    XLSX.utils.sheet_add_aoa(dataSheet, aoa, { origin: -1 });
    processed += slice.length;
    onProgress?.({
      phase: "building",
      processed,
      total,
      attempt,
      message: `Processed ${processed.toLocaleString()} of ${total.toLocaleString()} rows…`,
    });
    await tick();
  }

  XLSX.utils.book_append_sheet(wb, dataSheet, "Data");

  checkAborted(signal);
  onProgress?.({ phase: "writing", processed, total, attempt, message: "Writing workbook file…" });
  await tick();
  const arrayBuffer = XLSX.write(wb, { type: "array", bookType: "xlsx" });
  const blob = new Blob([arrayBuffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  onProgress?.({ phase: "done", processed, total, attempt, message: "Ready to download." });
  return blob;
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function tick() {
  return new Promise<void>((r) => setTimeout(r, 0));
}
