#!/usr/bin/env bash
# DEMO / LOCAL ONLY. Starts the local Supabase stack, loads the demo seed, and runs the app.
# Never links a hosted project and never runs db push.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v supabase >/dev/null 2>&1; then
  echo "Install the Supabase CLI and retry. Do not point it at a hosted project."
  exit 1
fi

supabase start

DB_URL="$(supabase status -o env | sed -n 's/^DB_URL="//p' | sed 's/"$//')"
if [[ -z "${DB_URL}" ]]; then
  DB_URL="$(supabase status -o env | sed -n 's/^DB_URL=//p')"
fi

# Apply repo migrations in a real transaction. The CLI skips its wrapper on
# 20260928040000 because that file contains plpgsql BEGIN, and LOCK TABLE then fails.
psql "${DB_URL}" -v ON_ERROR_STOP=1 -c "create schema if not exists supabase_migrations; create table if not exists supabase_migrations.schema_migrations (version text primary key, name text);"
for f in supabase/migrations/*.sql; do
  version="$(basename "$f" | cut -d_ -f1)"
  name="$(basename "$f" .sql)"
  already="$(psql "${DB_URL}" -tAc "select 1 from supabase_migrations.schema_migrations where version = '${version}'" 2>/dev/null || true)"
  if [[ "${already}" == "1" ]]; then
    continue
  fi
  psql "${DB_URL}" -v ON_ERROR_STOP=1 --single-transaction -f "$f"
  psql "${DB_URL}" -v ON_ERROR_STOP=1 -c "insert into supabase_migrations.schema_migrations (version, name) values ('${version}', '${name}') on conflict (version) do nothing"
done

psql "${DB_URL}" -v ON_ERROR_STOP=1 -f supabase/seed-demo.sql

supabase status -o env > /tmp/mml-supabase-status.env
# shellcheck disable=SC1091
set -a
source /tmp/mml-supabase-status.env
set +a

cat > .env.local <<EOF
# Generated by scripts/demo-local.sh. Local Supabase only. Do not commit.
VITE_SUPABASE_URL=${API_URL}
VITE_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
VITE_SUPABASE_PROJECT_ID=local
SUPABASE_URL=${API_URL}
SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
EOF

echo "Demo users: admin.demo@mml.local / ops.demo@mml.local  password DemoLocal!2026"
echo "App: http://127.0.0.1:8080"
exec npm run dev -- --host 127.0.0.1 --port 8080
