/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgentIntegrationsRouteImport } from './routes/_authenticated/agent-integrations'
import { Route as AuthenticatedAiCommandCenterRouteImport } from './routes/_authenticated/ai-command-center'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEntryRouteImport } from './routes/_authenticated/entry'
import { Route as AuthenticatedMcpAuditRouteImport } from './routes/_authenticated/mcp-audit'
import { Route as AuthenticatedPrivateCloudRouteImport } from './routes/_authenticated/private-cloud'
import { Route as AuthenticatedPublicCloudRouteImport } from './routes/_authenticated/public-cloud'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSyncStatusRouteImport } from './routes/_authenticated/sync-status'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAiCommandCenterAgentsRouteImport } from './routes/_authenticated/ai-command-center.agents'
import { Route as AuthenticatedAiCommandCenterAuditRouteImport } from './routes/_authenticated/ai-command-center.audit'
import { Route as AuthenticatedAiCommandCenterInboxRouteImport } from './routes/_authenticated/ai-command-center.inbox'
import { Route as AuthenticatedAiCommandCenterRunNowRouteImport } from './routes/_authenticated/ai-command-center.run-now'
import { Route as AuthenticatedMmlLabBatchesRouteImport } from './routes/_authenticated/mml-lab.batches'
import { Route as AuthenticatedMmlLabCostCatalogRouteImport } from './routes/_authenticated/mml-lab.cost-catalog'
import { Route as AuthenticatedMmlLabLabCatalogRouteImport } from './routes/_authenticated/mml-lab.lab-catalog'
import { Route as ApiPublicBulkTemplateVersionRouteImport } from './routes/api/public/bulk-template-version'
import { Route as ApiPublicHooksBulkImportCleanupRouteImport } from './routes/api/public/hooks/bulk-import-cleanup'
import { Route as ApiPublicHooksFreshdeskSyncRouteImport } from './routes/api/public/hooks/freshdesk-sync'
import { Route as ApiPublicHooksMcpSyncRouteImport } from './routes/api/public/hooks/mcp-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentIntegrationsRoute =
  AuthenticatedAgentIntegrationsRouteImport.update({
    id: '/agent-integrations',
    path: '/agent-integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiCommandCenterRoute =
  AuthenticatedAiCommandCenterRouteImport.update({
    id: '/ai-command-center',
    path: '/ai-command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntryRoute = AuthenticatedEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcpAuditRoute = AuthenticatedMcpAuditRouteImport.update({
  id: '/mcp-audit',
  path: '/mcp-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivateCloudRoute =
  AuthenticatedPrivateCloudRouteImport.update({
    id: '/private-cloud',
    path: '/private-cloud',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPublicCloudRoute =
  AuthenticatedPublicCloudRouteImport.update({
    id: '/public-cloud',
    path: '/public-cloud',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyncStatusRoute = AuthenticatedSyncStatusRouteImport.update({
  id: '/sync-status',
  path: '/sync-status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAiCommandCenterAgentsRoute =
  AuthenticatedAiCommandCenterAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAiCommandCenterRoute,
  } as any)
const AuthenticatedAiCommandCenterAuditRoute =
  AuthenticatedAiCommandCenterAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAiCommandCenterRoute,
  } as any)
const AuthenticatedAiCommandCenterInboxRoute =
  AuthenticatedAiCommandCenterInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedAiCommandCenterRoute,
  } as any)
const AuthenticatedAiCommandCenterRunNowRoute =
  AuthenticatedAiCommandCenterRunNowRouteImport.update({
    id: '/run-now',
    path: '/run-now',
    getParentRoute: () => AuthenticatedAiCommandCenterRoute,
  } as any)
const AuthenticatedMmlLabBatchesRoute =
  AuthenticatedMmlLabBatchesRouteImport.update({
    id: '/mml-lab/batches',
    path: '/mml-lab/batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMmlLabCostCatalogRoute =
  AuthenticatedMmlLabCostCatalogRouteImport.update({
    id: '/mml-lab/cost-catalog',
    path: '/mml-lab/cost-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMmlLabLabCatalogRoute =
  AuthenticatedMmlLabLabCatalogRouteImport.update({
    id: '/mml-lab/lab-catalog',
    path: '/mml-lab/lab-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBulkTemplateVersionRoute =
  ApiPublicBulkTemplateVersionRouteImport.update({
    id: '/api/public/bulk-template-version',
    path: '/api/public/bulk-template-version',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBulkImportCleanupRoute =
  ApiPublicHooksBulkImportCleanupRouteImport.update({
    id: '/api/public/hooks/bulk-import-cleanup',
    path: '/api/public/hooks/bulk-import-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFreshdeskSyncRoute =
  ApiPublicHooksFreshdeskSyncRouteImport.update({
    id: '/api/public/hooks/freshdesk-sync',
    path: '/api/public/hooks/freshdesk-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMcpSyncRoute = ApiPublicHooksMcpSyncRouteImport.update({
  id: '/api/public/hooks/mcp-sync',
  path: '/api/public/hooks/mcp-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agent-integrations': typeof AuthenticatedAgentIntegrationsRoute
  '/ai-command-center': typeof AuthenticatedAiCommandCenterRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entry': typeof AuthenticatedEntryRoute
  '/mcp-audit': typeof AuthenticatedMcpAuditRoute
  '/private-cloud': typeof AuthenticatedPrivateCloudRoute
  '/public-cloud': typeof AuthenticatedPublicCloudRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sync-status': typeof AuthenticatedSyncStatusRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ai-command-center/agents': typeof AuthenticatedAiCommandCenterAgentsRoute
  '/ai-command-center/audit': typeof AuthenticatedAiCommandCenterAuditRoute
  '/ai-command-center/inbox': typeof AuthenticatedAiCommandCenterInboxRoute
  '/ai-command-center/run-now': typeof AuthenticatedAiCommandCenterRunNowRoute
  '/mml-lab/batches': typeof AuthenticatedMmlLabBatchesRoute
  '/mml-lab/cost-catalog': typeof AuthenticatedMmlLabCostCatalogRoute
  '/mml-lab/lab-catalog': typeof AuthenticatedMmlLabLabCatalogRoute
  '/api/public/bulk-template-version': typeof ApiPublicBulkTemplateVersionRoute
  '/api/public/hooks/bulk-import-cleanup': typeof ApiPublicHooksBulkImportCleanupRoute
  '/api/public/hooks/freshdesk-sync': typeof ApiPublicHooksFreshdeskSyncRoute
  '/api/public/hooks/mcp-sync': typeof ApiPublicHooksMcpSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agent-integrations': typeof AuthenticatedAgentIntegrationsRoute
  '/ai-command-center': typeof AuthenticatedAiCommandCenterRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entry': typeof AuthenticatedEntryRoute
  '/mcp-audit': typeof AuthenticatedMcpAuditRoute
  '/private-cloud': typeof AuthenticatedPrivateCloudRoute
  '/public-cloud': typeof AuthenticatedPublicCloudRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sync-status': typeof AuthenticatedSyncStatusRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ai-command-center/agents': typeof AuthenticatedAiCommandCenterAgentsRoute
  '/ai-command-center/audit': typeof AuthenticatedAiCommandCenterAuditRoute
  '/ai-command-center/inbox': typeof AuthenticatedAiCommandCenterInboxRoute
  '/ai-command-center/run-now': typeof AuthenticatedAiCommandCenterRunNowRoute
  '/mml-lab/batches': typeof AuthenticatedMmlLabBatchesRoute
  '/mml-lab/cost-catalog': typeof AuthenticatedMmlLabCostCatalogRoute
  '/mml-lab/lab-catalog': typeof AuthenticatedMmlLabLabCatalogRoute
  '/api/public/bulk-template-version': typeof ApiPublicBulkTemplateVersionRoute
  '/api/public/hooks/bulk-import-cleanup': typeof ApiPublicHooksBulkImportCleanupRoute
  '/api/public/hooks/freshdesk-sync': typeof ApiPublicHooksFreshdeskSyncRoute
  '/api/public/hooks/mcp-sync': typeof ApiPublicHooksMcpSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agent-integrations': typeof AuthenticatedAgentIntegrationsRoute
  '/_authenticated/ai-command-center': typeof AuthenticatedAiCommandCenterRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entry': typeof AuthenticatedEntryRoute
  '/_authenticated/mcp-audit': typeof AuthenticatedMcpAuditRoute
  '/_authenticated/private-cloud': typeof AuthenticatedPrivateCloudRoute
  '/_authenticated/public-cloud': typeof AuthenticatedPublicCloudRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sync-status': typeof AuthenticatedSyncStatusRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/ai-command-center/agents': typeof AuthenticatedAiCommandCenterAgentsRoute
  '/_authenticated/ai-command-center/audit': typeof AuthenticatedAiCommandCenterAuditRoute
  '/_authenticated/ai-command-center/inbox': typeof AuthenticatedAiCommandCenterInboxRoute
  '/_authenticated/ai-command-center/run-now': typeof AuthenticatedAiCommandCenterRunNowRoute
  '/_authenticated/mml-lab/batches': typeof AuthenticatedMmlLabBatchesRoute
  '/_authenticated/mml-lab/cost-catalog': typeof AuthenticatedMmlLabCostCatalogRoute
  '/_authenticated/mml-lab/lab-catalog': typeof AuthenticatedMmlLabLabCatalogRoute
  '/api/public/bulk-template-version': typeof ApiPublicBulkTemplateVersionRoute
  '/api/public/hooks/bulk-import-cleanup': typeof ApiPublicHooksBulkImportCleanupRoute
  '/api/public/hooks/freshdesk-sync': typeof ApiPublicHooksFreshdeskSyncRoute
  '/api/public/hooks/mcp-sync': typeof ApiPublicHooksMcpSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/agent-integrations'
    | '/ai-command-center'
    | '/customers'
    | '/dashboard'
    | '/entry'
    | '/mcp-audit'
    | '/private-cloud'
    | '/public-cloud'
    | '/reports'
    | '/sync-status'
    | '/tickets'
    | '/transactions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ai-command-center/agents'
    | '/ai-command-center/audit'
    | '/ai-command-center/inbox'
    | '/ai-command-center/run-now'
    | '/mml-lab/batches'
    | '/mml-lab/cost-catalog'
    | '/mml-lab/lab-catalog'
    | '/api/public/bulk-template-version'
    | '/api/public/hooks/bulk-import-cleanup'
    | '/api/public/hooks/freshdesk-sync'
    | '/api/public/hooks/mcp-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/agent-integrations'
    | '/ai-command-center'
    | '/customers'
    | '/dashboard'
    | '/entry'
    | '/mcp-audit'
    | '/private-cloud'
    | '/public-cloud'
    | '/reports'
    | '/sync-status'
    | '/tickets'
    | '/transactions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ai-command-center/agents'
    | '/ai-command-center/audit'
    | '/ai-command-center/inbox'
    | '/ai-command-center/run-now'
    | '/mml-lab/batches'
    | '/mml-lab/cost-catalog'
    | '/mml-lab/lab-catalog'
    | '/api/public/bulk-template-version'
    | '/api/public/hooks/bulk-import-cleanup'
    | '/api/public/hooks/freshdesk-sync'
    | '/api/public/hooks/mcp-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/agent-integrations'
    | '/_authenticated/ai-command-center'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/entry'
    | '/_authenticated/mcp-audit'
    | '/_authenticated/private-cloud'
    | '/_authenticated/public-cloud'
    | '/_authenticated/reports'
    | '/_authenticated/sync-status'
    | '/_authenticated/tickets'
    | '/_authenticated/transactions'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/ai-command-center/agents'
    | '/_authenticated/ai-command-center/audit'
    | '/_authenticated/ai-command-center/inbox'
    | '/_authenticated/ai-command-center/run-now'
    | '/_authenticated/mml-lab/batches'
    | '/_authenticated/mml-lab/cost-catalog'
    | '/_authenticated/mml-lab/lab-catalog'
    | '/api/public/bulk-template-version'
    | '/api/public/hooks/bulk-import-cleanup'
    | '/api/public/hooks/freshdesk-sync'
    | '/api/public/hooks/mcp-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBulkTemplateVersionRoute: typeof ApiPublicBulkTemplateVersionRoute
  ApiPublicHooksBulkImportCleanupRoute: typeof ApiPublicHooksBulkImportCleanupRoute
  ApiPublicHooksFreshdeskSyncRoute: typeof ApiPublicHooksFreshdeskSyncRoute
  ApiPublicHooksMcpSyncRoute: typeof ApiPublicHooksMcpSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-integrations': {
      id: '/_authenticated/agent-integrations'
      path: '/agent-integrations'
      fullPath: '/agent-integrations'
      preLoaderRoute: typeof AuthenticatedAgentIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-command-center': {
      id: '/_authenticated/ai-command-center'
      path: '/ai-command-center'
      fullPath: '/ai-command-center'
      preLoaderRoute: typeof AuthenticatedAiCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry': {
      id: '/_authenticated/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof AuthenticatedEntryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp-audit': {
      id: '/_authenticated/mcp-audit'
      path: '/mcp-audit'
      fullPath: '/mcp-audit'
      preLoaderRoute: typeof AuthenticatedMcpAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/private-cloud': {
      id: '/_authenticated/private-cloud'
      path: '/private-cloud'
      fullPath: '/private-cloud'
      preLoaderRoute: typeof AuthenticatedPrivateCloudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/public-cloud': {
      id: '/_authenticated/public-cloud'
      path: '/public-cloud'
      fullPath: '/public-cloud'
      preLoaderRoute: typeof AuthenticatedPublicCloudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sync-status': {
      id: '/_authenticated/sync-status'
      path: '/sync-status'
      fullPath: '/sync-status'
      preLoaderRoute: typeof AuthenticatedSyncStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-command-center/agents': {
      id: '/_authenticated/ai-command-center/agents'
      path: '/agents'
      fullPath: '/ai-command-center/agents'
      preLoaderRoute: typeof AuthenticatedAiCommandCenterAgentsRouteImport
      parentRoute: typeof AuthenticatedAiCommandCenterRoute
    }
    '/_authenticated/ai-command-center/audit': {
      id: '/_authenticated/ai-command-center/audit'
      path: '/audit'
      fullPath: '/ai-command-center/audit'
      preLoaderRoute: typeof AuthenticatedAiCommandCenterAuditRouteImport
      parentRoute: typeof AuthenticatedAiCommandCenterRoute
    }
    '/_authenticated/ai-command-center/inbox': {
      id: '/_authenticated/ai-command-center/inbox'
      path: '/inbox'
      fullPath: '/ai-command-center/inbox'
      preLoaderRoute: typeof AuthenticatedAiCommandCenterInboxRouteImport
      parentRoute: typeof AuthenticatedAiCommandCenterRoute
    }
    '/_authenticated/ai-command-center/run-now': {
      id: '/_authenticated/ai-command-center/run-now'
      path: '/run-now'
      fullPath: '/ai-command-center/run-now'
      preLoaderRoute: typeof AuthenticatedAiCommandCenterRunNowRouteImport
      parentRoute: typeof AuthenticatedAiCommandCenterRoute
    }
    '/_authenticated/mml-lab/batches': {
      id: '/_authenticated/mml-lab/batches'
      path: '/mml-lab/batches'
      fullPath: '/mml-lab/batches'
      preLoaderRoute: typeof AuthenticatedMmlLabBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mml-lab/cost-catalog': {
      id: '/_authenticated/mml-lab/cost-catalog'
      path: '/mml-lab/cost-catalog'
      fullPath: '/mml-lab/cost-catalog'
      preLoaderRoute: typeof AuthenticatedMmlLabCostCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mml-lab/lab-catalog': {
      id: '/_authenticated/mml-lab/lab-catalog'
      path: '/mml-lab/lab-catalog'
      fullPath: '/mml-lab/lab-catalog'
      preLoaderRoute: typeof AuthenticatedMmlLabLabCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bulk-template-version': {
      id: '/api/public/bulk-template-version'
      path: '/api/public/bulk-template-version'
      fullPath: '/api/public/bulk-template-version'
      preLoaderRoute: typeof ApiPublicBulkTemplateVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bulk-import-cleanup': {
      id: '/api/public/hooks/bulk-import-cleanup'
      path: '/api/public/hooks/bulk-import-cleanup'
      fullPath: '/api/public/hooks/bulk-import-cleanup'
      preLoaderRoute: typeof ApiPublicHooksBulkImportCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/freshdesk-sync': {
      id: '/api/public/hooks/freshdesk-sync'
      path: '/api/public/hooks/freshdesk-sync'
      fullPath: '/api/public/hooks/freshdesk-sync'
      preLoaderRoute: typeof ApiPublicHooksFreshdeskSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mcp-sync': {
      id: '/api/public/hooks/mcp-sync'
      path: '/api/public/hooks/mcp-sync'
      fullPath: '/api/public/hooks/mcp-sync'
      preLoaderRoute: typeof ApiPublicHooksMcpSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAiCommandCenterRouteChildren {
  AuthenticatedAiCommandCenterAgentsRoute: typeof AuthenticatedAiCommandCenterAgentsRoute
  AuthenticatedAiCommandCenterAuditRoute: typeof AuthenticatedAiCommandCenterAuditRoute
  AuthenticatedAiCommandCenterInboxRoute: typeof AuthenticatedAiCommandCenterInboxRoute
  AuthenticatedAiCommandCenterRunNowRoute: typeof AuthenticatedAiCommandCenterRunNowRoute
}

const AuthenticatedAiCommandCenterRouteChildren: AuthenticatedAiCommandCenterRouteChildren =
  {
    AuthenticatedAiCommandCenterAgentsRoute:
      AuthenticatedAiCommandCenterAgentsRoute,
    AuthenticatedAiCommandCenterAuditRoute:
      AuthenticatedAiCommandCenterAuditRoute,
    AuthenticatedAiCommandCenterInboxRoute:
      AuthenticatedAiCommandCenterInboxRoute,
    AuthenticatedAiCommandCenterRunNowRoute:
      AuthenticatedAiCommandCenterRunNowRoute,
  }

const AuthenticatedAiCommandCenterRouteWithChildren =
  AuthenticatedAiCommandCenterRoute._addFileChildren(
    AuthenticatedAiCommandCenterRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentIntegrationsRoute: typeof AuthenticatedAgentIntegrationsRoute
  AuthenticatedAiCommandCenterRoute: typeof AuthenticatedAiCommandCenterRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntryRoute: typeof AuthenticatedEntryRoute
  AuthenticatedMcpAuditRoute: typeof AuthenticatedMcpAuditRoute
  AuthenticatedPrivateCloudRoute: typeof AuthenticatedPrivateCloudRoute
  AuthenticatedPublicCloudRoute: typeof AuthenticatedPublicCloudRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSyncStatusRoute: typeof AuthenticatedSyncStatusRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedMmlLabBatchesRoute: typeof AuthenticatedMmlLabBatchesRoute
  AuthenticatedMmlLabCostCatalogRoute: typeof AuthenticatedMmlLabCostCatalogRoute
  AuthenticatedMmlLabLabCatalogRoute: typeof AuthenticatedMmlLabLabCatalogRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentIntegrationsRoute: AuthenticatedAgentIntegrationsRoute,
  AuthenticatedAiCommandCenterRoute:
    AuthenticatedAiCommandCenterRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntryRoute: AuthenticatedEntryRoute,
  AuthenticatedMcpAuditRoute: AuthenticatedMcpAuditRoute,
  AuthenticatedPrivateCloudRoute: AuthenticatedPrivateCloudRoute,
  AuthenticatedPublicCloudRoute: AuthenticatedPublicCloudRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSyncStatusRoute: AuthenticatedSyncStatusRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedMmlLabBatchesRoute: AuthenticatedMmlLabBatchesRoute,
  AuthenticatedMmlLabCostCatalogRoute: AuthenticatedMmlLabCostCatalogRoute,
  AuthenticatedMmlLabLabCatalogRoute: AuthenticatedMmlLabLabCatalogRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBulkTemplateVersionRoute: ApiPublicBulkTemplateVersionRoute,
  ApiPublicHooksBulkImportCleanupRoute: ApiPublicHooksBulkImportCleanupRoute,
  ApiPublicHooksFreshdeskSyncRoute: ApiPublicHooksFreshdeskSyncRoute,
  ApiPublicHooksMcpSyncRoute: ApiPublicHooksMcpSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
