// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function readSupabaseRuntimeConfig() {
  return {
    url: import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || "",
    publishableKey:
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      "",
  };
}

export function getSupabaseConfigError(): string | null {
  const { url, publishableKey } = readSupabaseRuntimeConfig();
  const missing = [
    ...(url ? [] : ['SUPABASE_URL']),
    ...(publishableKey ? [] : ['SUPABASE_PUBLISHABLE_KEY']),
  ];
  if (missing.length === 0) return null;
  return `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
}


function createSupabaseClient() {
  const {
    url: SUPABASE_URL,
    publishableKey: SUPABASE_PUBLISHABLE_KEY,
  } = readSupabaseRuntimeConfig();

  const configError = getSupabaseConfigError();
  if (configError) {
    // DEV safety: render screens (auth/capture mode) even when backend env is not wired.
    // Production still fails closed unless explicit values are provided at build/runtime.
    if (import.meta.env.DEV) {
      console.warn(
        `[Supabase] ${configError} Using local placeholder values in DEV; network calls may fail until env is set.`,
      );
      return createClient<Database>(
        "http://127.0.0.1:54321",
        "sb_publishable_dev_placeholder",
        {
          global: {
            fetch: createSupabaseFetch("sb_publishable_dev_placeholder"),
          },
          auth: {
            storage: brokeredPreviewStorage(),
            persistSession: true,
            autoRefreshToken: true,
          },
        },
      );
    }
    console.error(`[Supabase] ${configError}`);
    throw new Error(
      `${configError} Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.`,
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

